---
- name: Add PPA
  apt_repository: repo="ppa:ondrej/php"

- name: Apt Update
  apt: update_cache=yes

- name: Install PHP and Dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php-fpm
    - php-cli
    - php-mysql
    - php-intl
    - php-ldap
    - php-sqlite3
    - php-curl
    - php7.2-xsl
    - php-imap
    - php-imagick
    - php-memcached
    - php-zip
    - php-mbstring
    - php-json
    - php-soap
    - php-xml

- name: Install Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 validate_certs=no

- name: Configure php7.2-fpm pool.
  lineinfile:
    dest: "/etc/php/7.2/fpm/pool.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^listen.?=.+$"
      line: "listen = /run/php/php7.2-fpm.sock"
    - regexp: "^pm.max_children.?=.+$"
      line: "pm.max_children = 120"
    - regexp: "^pm.start_servers.?=.+$"
      line: "pm.start_servers = 10"
    - regexp: "^pm.min_spare_servers.?=.+$"
      line: "pm.min_spare_servers = 10"
    - regexp: "^pm.max_spare_servers.?=.+$"
      line: "pm.max_spare_servers = 20"
    - regexp: "^;pm.max_requests.?=.+$"
      line: "pm.max_requests = 500"

- name: Configure php7.2 php.ini
  lineinfile:
    dest: "/etc/php/7.2/fpm/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^post_max_size.?=.+$"
      line: "post_max_size = 108M"
    - regexp: "^upload_max_filesize.?=.+$"
      line: "upload_max_filesize = 100M"
  notify: restart php-fpm
